#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 AppGrid Contributors
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Regenerates CHANGELOG.md from Conventional-Commit messages.
#
# Branch-aware: a single `git cliff` call walks only the current branch's
# ancestry, so tags that live on a maintenance branch (e.g. the 1.8.x patches on
# maintenance/1.8.x) would be missed. This covers the current branch in full,
# then each maintenance/* line up to its newest stable tag — discovered
# dynamically, no hardcoded versions or branch names.
#
# The per-range cliff blocks are then merged and ordered globally (Unreleased
# first, then by version descending) so a maintenance patch sits in version
# order rather than appended after the whole main line.
#
# Runs --offline so cliff doesn't enrich commits via the GitHub API. PR numbers
# still render — the Conventional Commits already carry "(#N)".

set -euo pipefail

cd "$(dirname "$0")/.."

ROOT=$(git rev-list --max-parents=0 HEAD | tail -1)

# Range 1: everything reachable from the current branch (its own line + every
# tag merged into it). Ranges 2..N: each maintenance line's released history.
ranges=("${ROOT}..HEAD")

# Unique maintenance line names, newest first. A line may exist locally,
# remotely, or both; collapse to one name and prefer the local checkout.
while IFS= read -r line; do
    [ -n "$line" ] || continue
    ref="$line"
    git rev-parse --verify -q "$ref" >/dev/null 2>&1 || ref="origin/$line"
    git rev-parse --verify -q "$ref" >/dev/null 2>&1 || continue
    # End the range at the line's newest STABLE tag that isn't already on HEAD.
    # Unreleased / rc-only maintenance work is deliberately excluded: the
    # changelog tracks released versions, and main's range is the only one that
    # contributes an Unreleased section. A line still in -rc adds nothing here.
    # `|| true`: grep exits 1 with no match, which would trip set -e / pipefail.
    tag=$(git tag --merged "$ref" --no-merged HEAD --sort=-v:refname 2>/dev/null \
          | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1 || true)
    [ -n "$tag" ] || continue
    ranges+=("HEAD..$tag")
done < <(
    git for-each-ref --format='%(refname:short)' \
        refs/heads/maintenance/ refs/remotes/origin/maintenance/ 2>/dev/null \
        | sed 's#^origin/##' | sort -urV
)

# Field separator between the sort key and the section body; record marker that
# stands in for a section's internal newlines so each section is one sort line.
# Both are control chars that never appear in changelog text.
SEP=$'\037'
NL=$'\036'

sections=$(
    for range in "${ranges[@]}"; do
        git cliff --offline --strip all "$range"
    done | awk -v sep="$SEP" -v nl="$NL" '
        function flush() {
            if (body == "") return
            gsub(/\n/, nl, body)
            print key sep body
            body = ""
        }
        /^## \[/ {
            flush()
            if ($0 ~ /\[Unreleased\]/)
                key = "9999.9999.9999"   # sort above every real version
            else { v = $0; sub(/^## \[/, "", v); sub(/\].*/, "", v); key = v }
            body = $0 "\n"
            next
        }
        { body = body $0 "\n" }
        END { flush() }
    ' | sort -t"$SEP" -k1,1 -rV | cut -d"$SEP" -f2- | tr "$NL" '\n'
)

{
    printf '# Changelog\n\n'
    printf '<!-- Auto-generated by scripts/changelog.sh from Conventional Commits.\n'
    printf '     Hand-edits get clobbered on the next run. Put release narrative\n'
    printf '     in the GitHub release notes (gh release create) instead. -->\n\n'
    printf 'All notable changes to AppGrid are documented here.\n\n'
    printf '%s\n' "$sections"
} > CHANGELOG.md

echo "wrote CHANGELOG.md ($(wc -l < CHANGELOG.md) lines) from ${#ranges[@]} range(s):"
printf '  %s\n' "${ranges[@]}"
