/*
    SPDX-FileCopyrightText: 2026 AppGrid Contributors
    SPDX-License-Identifier: GPL-2.0-or-later
*/

#include "appgridpanelplugin.h"

#include "popupsizepolicy.h"

#include <KConfigGroup>
#include <QTimer>

AppGridPanelPlugin::AppGridPanelPlugin(QObject *parent, const KPluginMetaData &data, const QVariantList &args)
    : AppGridPlugin(parent, data, args)
{
    m_useNativeActivation = true;

    // Deferred to ctor-completion so Plasma has finished wiring this applet
    // into its containment slot's config space before we read or write it.
    QTimer::singleShot(0, this, &AppGridPanelPlugin::restorePopupSizeIfStranger);
}

AppGridPanelPlugin::~AppGridPanelPlugin()
{
    // Alternatives-switch destroys the applet synchronously without firing
    // the expanded=false path that QML hooks into. Persist here so the
    // user's current size always reaches globalConfig before instance
    // death, no matter how the destruction was triggered.
    persistPopupSize();
}

void AppGridPanelPlugin::restorePopupSizeIfStranger()
{
    auto inst = config();
    auto global = globalConfig();

    const int instW = inst.readEntry(QStringLiteral("popupWidth"), -1);
    const int instH = inst.readEntry(QStringLiteral("popupHeight"), -1);
    const QString tag = inst.readEntry(QStringLiteral("popupSizeOwner"), QString());
    const int globalW = global.readEntry(QStringLiteral("appgridPopupWidth"), -1);
    const int globalH = global.readEntry(QStringLiteral("appgridPopupHeight"), -1);

    const auto action = PopupSizePolicy::decideRestore(instW, instH, tag, globalW, globalH);
    switch (action.kind) {
    case PopupSizePolicy::RestoreAction::Keep:
        return;
    case PopupSizePolicy::RestoreAction::Adopt:
        inst.writeEntry(QStringLiteral("popupWidth"), action.width);
        inst.writeEntry(QStringLiteral("popupHeight"), action.height);
        inst.writeEntry(QStringLiteral("popupSizeOwner"), PopupSizePolicy::ownerTag(action.width, action.height));
        break;
    case PopupSizePolicy::RestoreAction::Clear:
        // No trustworthy size anywhere — clear the foreign keys so AppletPopup
        // falls back to GridPanel's implicitWidth/Height instead of inheriting
        // the previous launcher's geometry.
        inst.deleteEntry(QStringLiteral("popupWidth"));
        inst.deleteEntry(QStringLiteral("popupHeight"));
        inst.deleteEntry(QStringLiteral("popupSizeOwner"));
        break;
    }
    inst.sync();
}

void AppGridPanelPlugin::persistPopupSize()
{
    auto inst = config();
    auto global = globalConfig();

    const int w = inst.readEntry(QStringLiteral("popupWidth"), 0);
    const int h = inst.readEntry(QStringLiteral("popupHeight"), 0);
    if (!PopupSizePolicy::isPersistable(w, h)) {
        return;
    }

    global.writeEntry(QStringLiteral("appgridPopupWidth"), w);
    global.writeEntry(QStringLiteral("appgridPopupHeight"), h);
    global.sync();

    inst.writeEntry(QStringLiteral("popupSizeOwner"), PopupSizePolicy::ownerTag(w, h));
    inst.sync();
}

// Metadata embedded Id-free (generated by CMake from metadata-panel.json.in
// with the KPlugin Id stripped); pluginId comes from the .so filename. The QML
// is compiled into this .so as qrc resources — see appgrid_add_compiled_applet
// in CMakeLists. (#173)
K_PLUGIN_CLASS_WITH_JSON(AppGridPanelPlugin, "metadata-panel.json")

#include "appgridpanelplugin.moc"
