/*
    SPDX-FileCopyrightText: 2026 AppGrid Contributors
    SPDX-License-Identifier: GPL-2.0-or-later
*/

#include "appgridplugin.h"

// Compiled-applet PoC (#173): QML is baked into the .so as a Plasma applet QML
// module; the metadata is embedded here, Id-free (generated by CMake from the
// package template). pluginId comes from the .so filename.
K_PLUGIN_CLASS_WITH_JSON(AppGridPlugin, "metadata-center.json")

#include "appgridplugin_register.moc"
